import Link from 'next/link';

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-4 bg-gray-950">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 flex items-center justify-between px-8 py-4 border-b border-gray-800 bg-gray-950/80 backdrop-blur z-10">
        <span className="font-bold text-lg tracking-tight">⚡ AI API Platform</span>
        <div className="flex gap-3">
          <Link href="/login" className="text-sm text-gray-400 hover:text-white px-4 py-2 rounded-lg transition">
            Login
          </Link>
          <Link href="/register" className="text-sm bg-indigo-600 hover:bg-indigo-500 px-4 py-2 rounded-lg font-medium transition">
            Get Started
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <div className="max-w-3xl text-center mt-20">
        <div className="inline-flex items-center gap-2 bg-indigo-950 border border-indigo-800 text-indigo-300 text-xs font-medium px-3 py-1 rounded-full mb-6">
          Powered by HuggingFace · DistilBART
        </div>
        <h1 className="text-5xl font-bold leading-tight mb-5 bg-gradient-to-br from-white to-gray-400 bg-clip-text text-transparent">
          Text Summarization API<br />for Developers
        </h1>
        <p className="text-gray-400 text-lg mb-8 leading-relaxed">
          Register, generate an API key, and start summarizing text in minutes.
          JWT-secured, rate-limited, with a full usage dashboard.
        </p>
        <div className="flex gap-3 justify-center">
          <Link href="/register" className="bg-indigo-600 hover:bg-indigo-500 px-6 py-3 rounded-xl font-medium transition text-sm">
            Start for free →
          </Link>
          <Link href="/docs" className="border border-gray-700 hover:border-gray-500 px-6 py-3 rounded-xl font-medium transition text-sm text-gray-300">
            View Docs
          </Link>
        </div>

        {/* Code preview */}
        <div className="mt-14 bg-gray-900 border border-gray-800 rounded-2xl p-5 text-left text-sm font-mono">
          <div className="flex gap-1.5 mb-4">
            <span className="w-3 h-3 rounded-full bg-red-500/70" />
            <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
            <span className="w-3 h-3 rounded-full bg-green-500/70" />
          </div>
          <pre className="text-gray-300 leading-relaxed overflow-x-auto">{`curl -X POST https://your-api.com/api/summarize \\
  -H "x-api-key: aip_your_key_here" \\
  -H "Content-Type: application/json" \\
  -d '{"text": "Your long article text..."}'

# Response
{
  "summary": "Concise summary generated by AI.",
  "latency_ms": 843
}`}</pre>
        </div>

        {/* Features */}
        <div className="grid grid-cols-3 gap-4 mt-10 text-left">
          {[
            { icon: '🔑', title: 'API Key Auth', desc: 'Generate and manage keys from your dashboard' },
            { icon: '📊', title: 'Usage Analytics', desc: '30-day request history with success/error breakdown' },
            { icon: '⚡', title: 'Rate Limiting', desc: 'Free: 100 req/day · Pro: 2,000 req/day' },
          ].map((f) => (
            <div key={f.title} className="bg-gray-900 border border-gray-800 rounded-xl p-4">
              <div className="text-2xl mb-2">{f.icon}</div>
              <div className="font-medium text-sm mb-1">{f.title}</div>
              <div className="text-gray-500 text-xs">{f.desc}</div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
